men_products = {
    1: {'name': 'Nike Air Force', 'price': 7999, 'image': 'images/men/andres-jasso-PqbL_mxmaUE-unsplash.jpg'},
    2: {'name': 'Adidas Ultraboost', 'price': 8999, 'image': 'images/men/adidas_ultraboost.jpg'},
    3: {'name': 'Asics Gel-Kayano 14', 'price': 11999, 'image': 'images/men/asics_gel_kayano.jpg'},
    4: {'name': 'Converse Chuck Taylor', 'price': 5499, 'image': 'images/men/converse_chuck.jpg'},
    5: {'name': 'Nike Flyknit', 'price': 16499, 'image': 'images/men/domino-studio-164_6wVEHfI-unsplash.jpg'},
    6: {'name': 'Fila Disruptor II', 'price': 10999, 'image': 'images/men/fila_disruptor.jpg'},
    7: {'name': 'Puma RS-X', 'price': 5999, 'image': 'images/men/irene-kredenets-dwKiHoqqxk8-unsplash.jpg'},
    8: {'name': 'Nike KD 10', 'price': 8599, 'image': 'images/men/luis-felipe-lins-LG88A2XgIXY-unsplash.jpg'},
    9: {'name': 'New Balance X90', 'price': 4999, 'image': 'images/men/maksim-larin-ezdrvzA1hZw-unsplash.jpg'},
    10: {'name': 'Nike Air Max 90', 'price': 8999, 'image': 'images/men/malvestida-DMl5gG0yWWY-unsplash.jpg'},
    11: {'name': 'New Balance 990v5', 'price': 7999, 'image': 'images/men/new_balance_990v5.jpg'},
    12: {'name': 'Adidas Ultraboost', 'price': 8999, 'image': 'images/men/paul-gaudriault-a-QH9MAAVNI-unsplash.jpg'},
    13: {'name': 'Puma RS-X Toys', 'price': 6499, 'image': 'images/men/puma_rsx.jpg'},
    14: {'name': 'Reebok Nano X', 'price': 7499, 'image': 'images/men/reebok_nano_x.jpg'},
    16: {'name': 'Skechers D’Lites', 'price': 10999, 'image': 'images/men/skechers_dlites.jpg'},
    17: {'name': 'Under Armour HOVR', 'price': 5999, 'image': 'images/men/ua_hovr.jpg'},
    18: {'name': 'Nike Metcon 9-LT', 'price': 8599, 'image': 'images/men/usama-akram-kP6knT7tjn4-unsplash.jpg'},
    21: {'name': 'Xavier', 'price': 2999, 'image': 'images/men/xavier-teo-SxAXphIPWeg-unsplash.jpg'},
    22: {'name': 'Air Jordan 1 Low', 'price': 8995, 'image': 'images/men/n1.jpg'},
    23: {'name': "Nike Air Force 1'07", 'price': 7495, 'image': 'images/men/n2.jpg'},
    24: {'name': 'Adidas SL 72 RS', 'price': 9999, 'image':'images/men/a2.jpg'},
    25: {'name': 'Nike Pegasus Plus', 'price': 16995, 'image': 'images/men/n3.jpg'},
    26: {'name': "Luka 4 PF 'Bloodline'", 'price': 11895, 'image': 'images/men/n4.jpg'},
    27: {'name': 'Nike Shox R4', 'price': 13995, 'image': 'images/men/n5.jpg'},
    28: {'name': "A'One 'Leo Lights' EP", 'price': 9695, 'image': 'images/men/n6.jpg'},
    29: {'name': "Nike Downshifter 13", 'price': 4295, 'image': 'images/men/n7.jpg'},
    30: {'name': "Nike Air Max Portal", 'price': 9695, 'image': 'images/men/n8.jpg'},
    31: {'name': "Nike Infinity Tour 2", 'price': 17495, 'image': 'images/men/n9.jpg'},
    32: {'name': "Air Max Dn8", 'price': 17495, 'image': 'images/men/n10.jpg'},
    33: {'name': "Air Jordan Legacy 312 Low", 'price': 12995, 'image': 'images/men/n11.jpg'},
    34: {'name': "Adidas SAMBA OG", 'price': 10999, 'image': 'images/men/a4.jpg'},
    35: {'name': "Adidas TrekForce", 'price': 2999, 'image': 'images/men/a5.jpg'},
    36: {'name': "Adizero EVO SL", 'price': 15999, 'image': 'images/men/a6.jpg'},
    37: {'name': "Adidas Campus 00s", 'price': 10999, 'image': 'images/men/a7.jpg'},
    38: {'name': "RUNFALCON 5", 'price': 6599, 'image': 'images/men/a8.jpg'},
    39: {'name': "PREDATOR LEAGUE FOLDOVER", 'price': 7999, 'image': 'images/men/a9.jpg'},
    40: {'name': "Copa Pure 3 CLUB INDOOR BOOTS", 'price': 3195, 'image': 'images/men/a10.jpg'},
    41: {'name': "Forum LOW CL", 'price': 10999, 'image': 'images/men/a11.jpg'},
    42: {'name': "Drop Step LOW 2.0 IKD", 'price': 7999, 'image': 'images/men/a12.jpg'}
}

# WOMEN
women_products = {
    1: {'name': 'Nike Blazer Mid', 'price': 7599, 'image': 'images/women/women1.jpg'},
    2: {'name': 'Adidas Forum Bold', 'price': 8299, 'image': 'images/women/women2.jpg'},
    3: {'name': 'Puma Cali Dream', 'price': 6999, 'image': 'images/women/women3.jpg'},
    4: {'name': 'New Balance 327', 'price': 8999, 'image': 'images/women/women4.jpg'},
    5: {'name': 'Reebok Club C', 'price': 4999, 'image': 'images/women/women5.jpg'},
    6: {'name': 'Asics Gel-Lyte', 'price': 6299, 'image': 'images/women/women6.jpg'},
    7: {'name': 'Skechers Uno', 'price': 5799, 'image': 'images/women/women7.jpg'},
    8: {'name': 'Under Armour Charged', 'price': 6899, 'image': 'images/women/women8.jpg'},
    9: {'name': 'Fila Ray Tracer', 'price': 4799, 'image': 'images/women/women9.jpg'},
    10: {'name': 'Converse Lift', 'price': 4299, 'image': 'images/women/women10.jpg'},
    11: {'name': 'Nike React Vision', 'price': 8999, 'image': 'images/women/women11.jpg'},
    12: {'name': 'Adidas Nizza', 'price': 5599, 'image': 'images/women/women12.jpg'},
    13: {'name': 'Puma RS-X³', 'price': 7699, 'image': 'images/women/women13.jpg'},
    14: {'name': 'Reebok Classic Leather', 'price': 4899, 'image': 'images/women/women14.jpg'},
    15: {'name': 'New Balance 550', 'price': 9899, 'image': 'images/women/women15.jpg'},
    16: {'name': 'Asics GT-2000', 'price': 8599, 'image': 'images/women/women16.jpg'},
    17: {'name': 'Skechers Max Cushioning', 'price': 6399, 'image': 'images/women/women17.jpg'},
    18: {'name': 'Fila Oakmont TR', 'price': 5199, 'image': 'images/women/women18.jpg'},
    19: {'name': 'Under Armour Flow', 'price': 7799, 'image': 'images/women/women19.jpg'},
    20: {'name': 'Converse Run Star Hike', 'price': 9499, 'image': 'images/women/women20.jpg'},
    21: {'name': 'Nike Air Force 1', 'price': 9499, 'image': 'images/men/ryan-plomp-jvoZ-Aux9aw-unsplash.jpg'}

}

# KIDS
kids_products = {
    1: {'name': 'Nike Pico 5', 'price': 2999, 'image': 'images/kids/kids1.jpg'},
    2: {'name': 'Adidas FortaRun', 'price': 3499, 'image': 'images/kids/kids2.jpg'},
    3: {'name': 'Puma Smash v2', 'price': 2899, 'image': 'images/kids/kids3.jpg'},
    4: {'name': 'Reebok Rush Runner', 'price': 3199, 'image': 'images/kids/kids4.jpg'},
    5: {'name': 'New Balance 515', 'price': 3799, 'image': 'images/kids/kids5.jpg'},
    6: {'name': 'Asics Contend 7', 'price': 3999, 'image': 'images/kids/kids6.jpg'},
    7: {'name': 'Skechers GoRun', 'price': 2799, 'image': 'images/kids/kids7.jpg'},
    8: {'name': 'Under Armour Rogue', 'price': 4199, 'image': 'images/kids/kids8.jpg'},
    9: {'name': 'Fila Kids Ray', 'price': 3099, 'image': 'images/kids/kids9.jpg'},
    10: {'name': 'Converse Kids CT', 'price': 2499, 'image': 'images/kids/kids10.jpg'},
    11: {'name': 'Nike Tanjun', 'price': 2699, 'image': 'images/kids/kids11.jpg'},
    12: {'name': 'Adidas Tensaur', 'price': 3199, 'image': 'images/kids/kids12.jpg'},
    13: {'name': 'Puma Wired', 'price': 2999, 'image': 'images/kids/kids13.jpg'},
    14: {'name': 'Reebok Flexagon', 'price': 3599, 'image': 'images/kids/kids14.jpg'},
    15: {'name': 'New Balance 574', 'price': 3999, 'image': 'images/kids/kids15.jpg'},
    16: {'name': 'Asics Noosa Tri', 'price': 3799, 'image': 'images/kids/kids16.jpg'},
    17: {'name': 'Skechers Microspec', 'price': 3299, 'image': 'images/kids/kids17.jpg'},
    18: {'name': 'Fila Disruptor Kids', 'price': 2899, 'image': 'images/kids/kids18.jpg'},
    19: {'name': 'Under Armour Assert', 'price': 3499, 'image': 'images/kids/kids19.jpg'},
    20: {'name': 'Converse Star Player', 'price': 2699, 'image': 'images/kids/kids20.jpg'}
}
